apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: quay-deploy-template
  namespace: demo
spec:
  params:
    - name: image-repository
    - name: image-tag
    - name: quay-repository
    - name: quay-namespace
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: quay-deploy-
        namespace: demo
      spec:
        pipelineRef:
          name: quay-deploy-pipeline
        params:
          - name: image-repository
            value: $(tt.params.image-repository)
          - name: image-tag
            value: $(tt.params.image-tag)
          - name: quay-repository
            value: $(tt.params.quay-repository)
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
        serviceAccountName: pipeline-sa
