apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: kubernetes-secrets
  labels:
    app: external-secrets-operator
spec:
  provider:
    kubernetes:
      remoteNamespace: secrets
      server:
        url: https://kubernetes.default
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: external-secrets
      auth:
        serviceAccount:
          name: eso-kubernetes-reader
          namespace: external-secrets-operator
