apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-pat
  namespace: demo
  labels:
    app: observability-demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-secrets
  target:
    name: github-pat
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: github-pat
        property: token
    - secretKey: username
      remoteRef:
        key: github-pat
        property: username
